Add ansible/python/ruby linters
epiphany-platform/azure-pipelines-agents pull request #1
Opened 2022-01-21 15:17 UTC by asciible

2022-01-21 15:22 UTC, cicharka approved these changes, later dismissed

2022-01-21 17:01 UTC, to-bar requested changes

2022-01-21 17:01 UTC, to-bar commented on docker-image/Dockerfile
> +        pip setuptools wheel lxml \
```suggestion
        pip setuptools wheel \
```

2022-01-21 17:01 UTC, to-bar commented on docker-image/Dockerfile
> +        ansible-lint-junit==0.16 \
Please add a comment why we use 0.16 or remove fixed version

2022-01-21 18:59 UTC, to-bar requested changes

2022-01-21 18:59 UTC, to-bar commented on docker-image/Dockerfile
> +# ansible-lint-junit==0.16 version specified because default version installed by pip fails to execute
```suggestion
# lxml is required to build ansible-lint-junit wheel
```

2022-01-21 18:59 UTC, to-bar commented on docker-image/Dockerfile
> +        ansible-lint-junit==0.16 \
```suggestion
        ansible-lint \
        ansible-lint-junit>=0.16 \
        boto3 \
        jinja2 \
        pylint \
        pylint-fail-under \
        pytest \
        python-json-logger \
        ruamel.yaml \
```
Let's keep alphabetical order. The latest ansible-lint-junit in PyPI is 0.16 so I'm not sure if we need to set it. If yes, maybe >=0.16 would be better?

2022-01-21 18:59 UTC, to-bar commented on docker-image/Dockerfile
>          pip setuptools wheel \
```suggestion
        lxml pip setuptools wheel \
```
It turned out that lxml is required (I've built image locally with `--no-cache=true`).

2022-01-25 09:09 UTC, to-bar approved these changes

2022-01-25 09:46 UTC, seriva approved these changes

2022-01-25 20:27 UTC, merged